hw3: DictionaryBST.cpp DictionarySearchTree.cpp DictionaryAVLTree.cpp Dictionary23Tree.cpp  main.cpp
	g++ DictionaryBST.cpp DictionarySearchTree.cpp DictionaryAVLTree.cpp Dictionary23Tree.cpp  main.cpp -o hw3
